project_id = "hfpvnsbiewudpqbtlvte"

[auth]
enable_signup = false
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://1d25a9da-8986-4a5d-886a-1b216e7f3cc9.lovableproject.com/**",
  "https://4c93e081-c64d-4029-b9b2-6d1e2ba91c4d.lovableproject.com/**",
  "https://id-preview--1d25a9da-8986-4a5d-886a-1b216e7f3cc9.lovable.app/**",
  "https://id-preview--4c93e081-c64d-4029-b9b2-6d1e2ba91c4d.lovable.app/**",
  "https://montekristo-web-forge.lovable.app/**",
  "https://preview--montekristo-web-forge.lovable.app/**",
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"

[functions.escalate-overdue-tasks]
verify_jwt = false

[functions.travelnet-webhook]
verify_jwt = false