/**
 * Picture - universal <picture> wrapper for AVIF + WebP format fallback.
 *
 * Usage (basic, single-size):
 *   <Picture src="/images/icon-brain" alt="AI brain icon" width={40} height={40} />
 *
 * Usage (responsive hero with srcset):
 *   <Picture
 *     src="/images/hero-bg"
 *     alt=""
 *     width={1920}
 *     height={1080}
 *     responsive
 *     widths={[640, 960, 1280, 1920]}
 *     sizes="100vw"
 *     loading="eager"
 *     fetchPriority="high"
 *   />
 *
 * Conventions:
 *   - `src` is the base path WITHOUT extension. Files at `${src}.avif` and `${src}.webp`
 *     must exist at build time (generated by scripts/optimize-images.mjs).
 *   - For responsive, `${src}-${w}.avif` and `${src}-${w}.webp` must exist for each `w` in `widths`.
 *   - Decorative images should pass `alt=""` (per WCAG). Content images require meaningful alt.
 *   - Default `loading="lazy"` + `decoding="async"` for everything except above-the-fold.
 */
import type { CSSProperties } from "react";

interface PictureProps {
  src: string;
  alt: string;
  width: number;
  height: number;
  className?: string;
  style?: CSSProperties;
  loading?: "lazy" | "eager";
  fetchPriority?: "high" | "low" | "auto";
  decoding?: "async" | "sync" | "auto";
  responsive?: boolean;
  widths?: number[];
  sizes?: string;
}

export default function Picture({
  src,
  alt,
  width,
  height,
  className,
  style,
  loading = "lazy",
  fetchPriority = "auto",
  decoding = "async",
  responsive = false,
  widths = [640, 960, 1280, 1920],
  sizes = "100vw",
}: PictureProps) {
  const buildSrcSet = (ext: "avif" | "webp") => {
    if (!responsive) return `${src}.${ext}`;
    return widths.map((w) => `${src}-${w}.${ext} ${w}w`).join(", ");
  };

  return (
    <picture>
      <source type="image/avif" srcSet={buildSrcSet("avif")} sizes={responsive ? sizes : undefined} />
      <source type="image/webp" srcSet={buildSrcSet("webp")} sizes={responsive ? sizes : undefined} />
      <img
        src={`${src}.webp`}
        alt={alt}
        width={width}
        height={height}
        className={className}
        style={style}
        loading={loading}
        decoding={decoding}
        fetchPriority={fetchPriority}
      />
    </picture>
  );
}
