INSERT INTO public.track_clean_types (track_id, type, code, name, active) VALUES
  (3, 'inspection', 'Inspection', 'Inspection', TRUE),
  (4, 'clean', 'Final', 'Final Clean', TRUE),
  (5, 'clean', 'DC', 'Deep Clean', FALSE),
  (6, 'inspection', 'PA Inspect', 'Owner Arrival Checklist', FALSE),
  (7, 'clean', 'Mandatory', 'Mandatory Clean', TRUE),
  (8, 'clean', 'TOUCH', 'Touch Up Clean', TRUE),
  (9, 'clean', 'Daily', 'Daily Clean', TRUE),
  (10, 'clean', 'Random', 'Intermittent Clean', TRUE),
  (11, 'clean', 'Linen Chan', 'Linen Change', TRUE),
  (12, 'clean', 'DeepCleanM', 'Deep Clean - MGMT', TRUE),
  (13, 'clean', 'GRD', 'GR - departure task', FALSE),
  (14, 'clean', 'DI', 'Damage Inspection', FALSE),
  (15, 'inspection', 'GRA', 'GRA - Pre-Arrival Tasks', FALSE),
  (16, 'clean', '(O)Random1', 'Owner Random HK - 1H', TRUE),
  (17, 'clean', '(O)RandomW', 'Owner Random HK - W', TRUE),
  (18, 'clean', '(O)RandomM', 'Owner Random HK - MGMT', TRUE),
  (19, 'clean', '(O)RandomS', 'Owner Random HK - Setai', TRUE),
  (20, 'clean', '(O)Daily1H', 'Owner Daily HK - 1H', TRUE),
  (21, 'clean', '(O)DailyW', 'Owner Daily HK - W', TRUE),
  (22, 'clean', '(O)DailyMG', 'Owner Daily HK - MGMT', TRUE),
  (23, 'clean', '(O)DailySe', 'Owner Daily HK - Setai', TRUE),
  (24, 'clean', '(O)Touch1H', 'Owner Touch Up HK - 1H', TRUE),
  (25, 'clean', '(O)TouchW', 'Owner Touch Up HK - W', TRUE),
  (26, 'clean', '(O)TouchMG', 'Owner Touch Up HK - MGMT', TRUE),
  (27, 'clean', '(O)TouchSe', 'Owner Touch Up HK - Setai', TRUE),
  (28, 'clean', 'PSC', 'Photoshoot Cleaning', TRUE),
  (29, 'clean', 'CNCL', 'HK Cancellation', TRUE),
  (30, 'clean', 'LINSETUP', 'Linen Setup', TRUE),
  (31, 'clean', 'PM Inspect', 'Property Management Inspection', TRUE),
  (32, 'clean', 'Quick Insp', 'HK Quick Inspection', TRUE),
  (33, 'clean', 'STRIP', 'Remove soiled linen & trash', TRUE),
  (34, 'clean', 'VCI', 'TEST - VCI Inspection', FALSE),
  (35, 'clean', 'STAIN', 'Treat Stain', TRUE),
  (36, 'inspection', 'OIS', 'Pre Owner Inspection - S', FALSE),
  (37, 'clean', 'Add''l Line', 'Additional Linen Delivery', TRUE),
  (38, 'clean', 'DEL', 'Delivery', TRUE),
  (39, 'clean', 'Quick Insp', 'Quick Inspection', TRUE),
  (40, 'clean', 'STAIN1H', 'Upholstery Treatment - 1H', TRUE),
  (41, 'clean', 'STAINW', 'Upholstery Treatment - W', TRUE),
  (42, 'clean', 'STAINSETAI', 'Upholstery Treatment - Setai', TRUE),
  (43, 'clean', 'STAINMGMT', 'Upholstery Treatment - MGMT', TRUE),
  (44, 'inspection', 'OI1H', 'Pre Owner Inspection - 1H', FALSE),
  (45, 'inspection', 'OIW', 'Pre Owner Inspection - W', FALSE),
  (46, 'inspection', 'OIMGMT', 'Pre Owner Inspection - MGMT', FALSE),
  (47, 'clean', 'MEETVENDOR', 'Meet Vendor', TRUE),
  (48, 'clean', 'PICKUP', 'Pickup', TRUE),
  (49, 'clean', 'Rug Gate 2', 'Rug Gate 2025', TRUE),
  (50, 'clean', 'CRIBDELIVE', 'Crib Delivery', TRUE),
  (51, 'clean', 'Touchup Ma', 'O - Touch Up after Maintenance', TRUE),
  (52, 'clean', 'DOK', 'Deliver Owner Keys', TRUE),
  (53, 'clean', 'POK', 'Pickup Owner Keys', TRUE),
  (54, 'clean', '25Summer', '2025 Summer Inspection', TRUE),
  (55, 'clean', 'KP', 'Key Project', TRUE),
  (56, 'clean', '(O)TGLASS1', 'O - Touch Up HK + Glass - 1H', TRUE),
  (57, 'clean', '(O)TGLASSM', 'O - Touch Up HK + Glass - MGMT', TRUE),
  (58, 'clean', '(O)TGLASSS', 'O - Touch Up HK + Glass - Setai', TRUE),
  (59, 'clean', '(O)TGLASSW', 'O - Touch Up HK + Glass - W', TRUE),
  (60, 'clean', 'BFC', 'Balcony Furniture Clean - Setai', TRUE),
  (61, 'clean', 'SOFC', 'Setai Owner / OG -  Final Clean', TRUE),
  (62, 'clean', 'DeepClean1', 'Deep Clean - 1H', TRUE),
  (63, 'clean', 'DeepCleanW', 'Deep Clean - W', TRUE),
  (64, 'clean', 'DeepCleanS', 'Deep Clean - Setai', TRUE),
  (65, 'inspection', 'PAOI', 'Delete', FALSE),
  (66, 'clean', 'DC-Floors1', 'Deep Clean (Floors) - 1H', TRUE),
  (67, 'clean', 'DC-FloorsM', 'Deep Clean (Floors) - MGMT', TRUE),
  (68, 'clean', 'DC-FloorsW', 'Deep Clean (Floors) - W', TRUE),
  (69, 'clean', 'DC-FloorsS', 'Deep Clean (Floors) - Setai', TRUE),
  (70, 'clean', 'BFC-O', 'Balcony Furniture Clean - SetaiO', TRUE),
  (71, 'clean', 'TaskInsp', 'Daily Task', TRUE),
  (72, 'clean', 'INFO need', 'Information Needed', TRUE),
  (73, 'clean', 'Office Wor', 'Office Work', TRUE),
  (74, 'clean', 'ODC', 'Owner Departure Checklist', TRUE),
  (75, 'clean', 'OACL', 'Owner Arrival Check List', TRUE),
  (76, 'clean', 'PI', 'Partial Inspection', TRUE),
  (77, 'clean', 'ONB', 'Onboarding Inspection - (inspect', TRUE),
  (78, 'clean', 'ONB INV', 'Onboarding Inventory', TRUE),
  (79, 'clean', 'ONVEO', 'Onboarding Essential Organizatio', TRUE)
ON CONFLICT (track_id) DO UPDATE SET type=EXCLUDED.type, code=EXCLUDED.code, name=EXCLUDED.name, active=EXCLUDED.active, synced_at=now();