-- Nemr Build Directive §22: hybrid Final Clean orchestrator.
--
-- AiiA waits for TRACK to push a Final Clean task for each departing
-- reservation. If TRACK doesn't push one within p_grace_hours of the
-- departure date, AiiA auto-creates one with external_source='aiia_generated'
-- so it deduplicates cleanly against TRACK pushes that may arrive later.
--
-- Schedule: every 30 min via pg_cron. Logs to audit_logs.
--
-- Re-running on the same reservation is safe because of the unique
-- constraint on (external_source, external_id); the synthetic id is
-- 'aiia-final-<reservation_id>'.

CREATE OR REPLACE FUNCTION public.create_missing_final_cleans(
  p_lookback_days integer DEFAULT 7,
  p_grace_hours integer DEFAULT 4
)
RETURNS TABLE (created_count integer, skipped_existing integer, skipped_no_unit integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_created integer := 0;
  v_skipped_existing integer := 0;
  v_skipped_no_unit integer := 0;
  r record;
  v_synth_external_id text;
  v_property_id uuid;
  v_unit_id uuid;
  v_unit_code text;
  v_dep_date date;
  v_today_miami date := (now() AT TIME ZONE 'America/New_York')::date;
BEGIN
  FOR r IN
    SELECT res.external_id, res.unit_id AS track_unit_id, res.departure_date::date AS dep_date, res.status
    FROM public.mv_track_reservations_latest res
    WHERE res.status NOT IN ('Cancelled', 'cancelled')
      AND res.departure_date IS NOT NULL
      AND res.departure_date::date < v_today_miami - (p_grace_hours / 24.0)::int
      AND res.departure_date::date >= v_today_miami - p_lookback_days
      AND res.unit_id IS NOT NULL
  LOOP
    -- Dedupe: skip if any housekeeping task already exists for this reservation
    -- (covers both TRACK-pushed and prior aiia_generated rows).
    IF EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.task_category = 'housekeeping'
        AND t.reservation_id = r.external_id
    ) THEN
      v_skipped_existing := v_skipped_existing + 1;
      CONTINUE;
    END IF;

    -- Resolve the local unit + property for the orphan reservation.
    SELECT u.id, u.property_id, COALESCE(u.short_name, u.unit_code)
    INTO v_unit_id, v_property_id, v_unit_code
    FROM public.units u
    WHERE u.track_id = r.track_unit_id
    LIMIT 1;

    IF v_unit_id IS NULL OR v_property_id IS NULL THEN
      v_skipped_no_unit := v_skipped_no_unit + 1;
      CONTINUE;
    END IF;

    v_synth_external_id := 'aiia-final-' || r.external_id;
    v_dep_date := r.dep_date;

    INSERT INTO public.tasks (
      title, description,
      property_id, unit_id,
      task_category, task_type, housekeeping_type,
      priority, status,
      requires_photo, requires_note, requires_timestamp,
      due_at, scheduled_for,
      source_type, external_source, external_id,
      reservation_id,
      created_at, updated_at
    )
    VALUES (
      'Final clean (auto) - ' || COALESCE(v_unit_code, 'Unit'),
      'Auto-generated by AiiA Final Clean orchestrator. TRACK did not push a housekeeping task for reservation '
        || r.external_id || ' within ' || p_grace_hours || 'h of departure.',
      v_property_id, v_unit_id,
      'housekeeping', 'checkout_turnover', 'checkout_clean',
      'high', 'new',
      true, true, true,
      v_dep_date::timestamptz + interval '6 hours',
      v_dep_date::timestamptz + interval '4 hours',
      'aiia_generated', 'aiia_generated', v_synth_external_id,
      r.external_id,
      now(), now()
    )
    ON CONFLICT (external_source, external_id) DO NOTHING;

    IF FOUND THEN
      v_created := v_created + 1;
    END IF;
  END LOOP;

  RETURN QUERY SELECT v_created, v_skipped_existing, v_skipped_no_unit;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.create_missing_final_cleans(integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_missing_final_cleans(integer, integer) TO authenticated, service_role;

-- Schedule every 30 minutes. Emits an audit_logs entry per run for visibility.
DO $$
BEGIN
  PERFORM cron.unschedule('final-clean-orchestrator-every-30min');
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

SELECT cron.schedule(
  'final-clean-orchestrator-every-30min',
  '*/30 * * * *',
  $cron$
    INSERT INTO public.audit_logs (action, entity_type, entity_id, description, payload_json)
    SELECT 'final_clean_orchestrator_run', 'system', gen_random_uuid(),
      'Final Clean orchestrator created=' || created_count
        || ' skipped_existing=' || skipped_existing
        || ' skipped_no_unit=' || skipped_no_unit,
      jsonb_build_object('severity', 'info',
        'created', created_count,
        'skipped_existing', skipped_existing,
        'skipped_no_unit', skipped_no_unit)
    FROM public.create_missing_final_cleans();
  $cron$
);
